apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.25.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
        - name: sidecar-stackdriver
          image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.8.2
          imagePullPolicy: Always
          args:
            - "--stackdriver.project-id={PROJECT_ID}"
            - "--prometheus.wal-directory={DATA.VOLUME}/wal"
            - "--prometheus.api-address=127.0.0.1:9090"
            - "--stackdriver.kubernetes.location={GCP.REGION}"
            - "--stackdriver.kubernetes.cluster-name={GCP.CLUSTER}"
          ports:
            - name: sidecar
              containerPort: 9091
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /prometheus

      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf

        - name: prometheus-storage-volume
          emptyDir: {}